@baseUrl = http://localhost:8080

### Ping/Health
GET {{baseUrl}}/ping
?? body contains pong

###---------------------
### Create a Warehouse                    
POST {{baseUrl}}/api/warehouses           
Content-Type: application/json            
                                            
{                                         
    "key": "DXB-01",                        
    "location": "Dubai",                    
    "priority": 1,                          
    "isActive": true                        
}  
?? body = Demo Handler